### PR TITLE
[RestAPI Speed] AsyncIO Gather tasks

### PR DESCRIPTION
**Pull request by cooperlees**
AsyncIO Gather RestAPI calls to achieve faster turn around time
- @ Ripe 73 Wifi with ~180ms latency we went from:
  real    1m6.660s
  to
  real    0m23.837s

Full Output: http://pastebin.com/Ly9k4JDB

### CODE REVIEW

**Comment by jpaussa** [comment]
This seems to break mysql. It worked once and then a second run just hung.

**Comment by cooperlees** [comment]
Ahhh dam. I'll actually test and debug.

**Comment by sdunster** [comment]
Make sure you don't try to use connections in multiple asyncio tasks - each connection can only support a single query + fetch at a time, although aiomysql probably handles this for you so I'm not sure what the issue is.

**Comment by cooperlees** [comment]
ok - We no longer connect and disconnect the pool for each query. Once I land this I'll really get stuck into smarter rest API'in so it's usable speed-wise.

**Pull request merged**
